sudo: required
services: docker
language: go
go:
- 1.9
env:
  global:
  - TERRAFORM_VERSION=v0.10.8
  - PATH=/home/travis/gopath/bin:$PATH DEBIAN_FRONTEND=noninteractive
  - secure: rEKBZer1rDx3heuTxu+iviVDdZRWTlstl8rJqnUW53fdg5tzdvORPckVTQ/NgzuBIw8vpjdlG2xZq+IRPa+qpYrshZBXsOH1GUIQSsZYEcnci/4iTsJtOR6BaUpkWTDOhHgJ+HFs/ffTZWZhXF2F5AddF9ebFUydIxLctlClU4RNqSP3ngWLXcdtBf8Ujk0uHnuyYVErZefZPiGZJWkHrZx94Sx0l1lL7YH8bejNtvFBO03Bt8Gey8paakU2SVKaQkUTYK+GWkOqfsLDAcvyuUbgco0MFgHG3NhM22zw/u0yRty8YZGy5QNbdrSjWrWPxGhTF6b/OeZ5baQSbaHQXU826FPWeJTcPjy21RtzVr6KNFpZ5ncE4OYDID+NjJKXIfOz6Ayhn0QA86z/U8/IzVk+sD+NNOHtAwKlwhHn62LdT8iVHn3jB800hdTjg0Z0kUL3eUB6jMPvWpOrkDEzpttZWFqkcuNbRBqA3Md9qX1YfNkRnM5xKPg9rcGog4SpsFU4QmDYOi4EoJQNcMc3ZRMy8bSiUjWUnzuuaZP4Q/Lk68KW9gi/me1SuqKMtUUd7xues+dkUyLXZydqT8BMEaDeWIwRtGG4JbEe8ouvSGJruH8u5XtqHVVl6tXq57nhXcTrC++jtSOol1lnurmw2pl9H47+OwzLPO/q27s/RO4=
  - secure: NdAMMFql3TrWIVPq4Jd6pevtl1KOPvpO3Qa4wj+Slsb5DLcnHVlL+EqY06fw9/n+YyvGOELVctMNh+WY1A5Xwh3IZiTGxWNcAsD/xBmm0f+aCW7/sjgCVhs0WuDfBMTVjIfCWChAQMTs4QsnQ2kvTsMXhzwNuDKD4jCbN+VafpOm6gDUXNnXkdajYwwp43xM3jzLOkr+IcsQmNi/bIClIY2fNXFCyhQMDnsablqDFuMaeyxJg5wiesh56qWpn8iwfRigtNDfWm40TSRpULYnnkWD2CsUTdJjuY6Z0AKBFUAA3xzmK9FwU/390JM7/EDxV2zz2nBTnNI2PtFxkkIWL5U6A/BxZGJc4QqwdSKn/Rv/9+CWImUZp9a9Kjw6+8pz4bZRKNqS1kgqXgc0dVK/oTNJwxGQvtYE6ZUqBsvueaEBB5CH4F2EwYtPxbjwfZVIsHyt8XwW8F19817qwl0VulsySKaIJxdcrEFrQqAIdMb5TqruC8tF9Vj1zfAx/t8hznTrRgIqWG1WKQJOoFD5k/ZwQt0Ao7ROM8BGW1deKxYCXuhGUjHj2N7uNZOZbYOZ7pdtR2ISKPSBjI6ARFivp3pB35Hmszfw4VBtYolbxdsbt2PgIYmULiHvAFLs72QwPCwHFShQ2NI6bUGhaCLpjx7otbaDje8Y7fzJuTDnTHc=
  - secure: TFj6AldmXgOxb0G0GAdEpAdDMftqh2vTFXbiIOQog1lT9AGLwCxkUrUzISfwTomP8155lDVE7Hdm9RoQO07yG0T+fdF7pAHHBBcfgTxXZntLQnrPzcp3JCf3Fe1RgHOhXR3QBoenBxi7PW3Dk+Hu6j9sBZGARaTP0/H3v0ECNUgVhd9SeDJrTflDVMGVXiKJ8mNp1skJF1z1BpxVfihYVxldZg8bWaF1Xe1SxpDMGNSUXnd2taFTpUFvvRS/PSK4ho7BlsOGpXy7g6d10I1Ff47Lm6zdDaPbLifpSyNeypc+yZ4uPopo2ddfKlC/jsDuR0fMN7B/H+gRyoP/myCgEUW67v3dGjC1p3erYdoavf/4suVvNNgPIZdKSpw6T75NvCEiPszVfJNntmHnwBo9TvN25FEDS1S7qFZvRSjpWNY0wM4M30DbfuDA9GQyigzC/ZzDs247fRvcD/anrAZg4+vJcMNOCW0bO107zsCzR603N5sdvFL3iAb97oy2b/CODumSOKdg6nYThRMn696fTftkj+7Zmzk/EA5h/F3gRhXu6n30HJIV6MDTTgJbcunNz6WJZRHpdQf/PG2gNbKEXXR9WDQlgysM/eVCafTBv2Y37rUaoK9xaulOtcvN+pDTqXJz1o02KZ6ZErmtDXFUedEWVOpqaKhPb4vvpao7epA=
install:
  - go get -u github.com/golang/lint/golint
script:
- make test
- make docker-build
before_deploy:
- go get github.com/aktau/github-release
- mkdir -p ~/bin
- git clone https://github.com/github/hub.git && cd hub && script/build -o ~/bin/hub
  && cd ..
- echo $TRAVIS_BRANCH
- git config --add remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*'
- git fetch
- git checkout master || git checkout -b master origin/master
- git checkout $TRAVIS_BRANCH
- git fetch --depth=1000
- git fetch --tags --depth=1000 || true
deploy:
- provider: script
  script: scripts/release.pl --task=upload-to-github-release && scripts/release.pl
    --task=upload-master-to-github-release && scripts/release_homebrew.sh
  skip_cleanup: true
  on:
    branch: master

- provider: script
  script: scripts/release.pl --task=create-pullrequest --current-branch=$TRAVIS_BRANCH
  skip_cleanup: true
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH =~ ^bump-version-.*$"
