site_name: Terraform for さくらのクラウド
site_url: https://yamamoto-febc.github.io/terraform-provider-sakuracloud/
site_description: Terrform for さくらのクラウド
site_author: '@yamamoto-febc'
repo_url: https://github.com/yamamoto-febc/terraform-provider-sakuracloud
repo_name: terraform-provider-sakuracloud
copyright: Copyright (C) 2017 Kazumichi Yamamoto.
google_analytics: ['UA-63739336-5','auto']
theme: readthedocs
extra_css:
  - css/extra.css
pages:
  - ホーム: index.md
  - ドキュメント:
    - インストールガイド: installation.md
    - ブログ/記事/読み物: articles.md
  - 設定リファレンス:
    - 全体/共通項目:
      - プロバイダ: configuration/provider.md
    - リソース:
      - サーバー: configuration/resources/server.md
      - ディスク: configuration/resources/disk.md
      - スイッチ: configuration/resources/switch.md
      - ルーター: configuration/resources/internet.md
      - サブネット: configuration/resources/subnet.md
      - パケットフィルタ: configuration/resources/packet_filter.md
      - ブリッジ: configuration/resources/bridge.md
      - ロードバランサー: configuration/resources/load_balancer.md
      - VPCルーター: configuration/resources/vpc_router.md
      - データベース: configuration/resources/database.md
      - スタートアップスクリプト: configuration/resources/note.md
      - 公開鍵: configuration/resources/ssh_key.md
      - 公開鍵(生成): configuration/resources/ssh_key_gen.md
      - DNS: configuration/resources/dns.md
      - GSLB: configuration/resources/gslb.md
      - シンプル監視: configuration/resources/simple_monitor.md
      - 自動バックアップ: configuration/resources/auto_backup.md
    - データソース:
      - データソース: configuration/resources/data_resource.md
